#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new ArgvInput);


DB_DATABASE=radonllcapimobel_llcapi
DB_USERNAME=radonllcapimobel_apillc
DB_PASSWORD=The009@1


DB_DATABASE=triumfoaenew
DB_USERNAME=aetriumfonew
DB_PASSWORD=The009@1


DB_DATABASE=triumfous_triumfolaravel
DB_USERNAME=triumfous_triumfous
DB_PASSWORD=The009@1
